version: '3.9'
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SENDER_EMAIL: akkireddybaladitya494@gmail.com
      SENDER_PASSWORD: yhsbcctnqponyvlc
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
