import random
import smtplib
import os

SENDER_EMAIL = "your-email@email.com" // if you have any doubts about it go and read the README file step one
SENDER_PASSWORD = "16-digit password generated by your gmail"// dont forget to enable this step in your gmail account
// dont forget to enable 2-step verification in your gmail account then only your email will allow this
def generate_otp():
    return str(random.randint(100000, 999999))

def send_otp_email(receiver, otp):
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        message = f"Subject: Your OTP\n\nYour OTP is: {otp}"
        server.sendmail(SENDER_EMAIL, receiver, message)
